version: '3'
services:
  bot-service:
    container_name: ecc-api-service
    image: jsamonte22/vibe:ecc-service-1.4.0
    ports:
      - 8000:3000
    environment:
      - DB_HOST=mysql-service
      - DB_USER=root
      - DB_PASS=vibetech@2024
      - DB_NAME=ecc-services
      - OPENAI_API_KEY=sk-svcacct-15TLehrlgPdbUFIkr1iPT3BlbkFJJlYWRY1kt1EV1JlK8uEU
      - OPENAI_ASSISTANT_ID=asst_sDllhwXTNgRtJNbUtfSIe9Fq
      - OPENAI_VECTOR_STORE_ID=vs_68PUrGHdmxcqVdzZkwkBbIBY
      - FB_VERIFY_TOKEN=vibetech@2024
      - FB_PAGE_ACCESS_TOKEN=EAAHXYxmRZAL8BOZC64S9VHHYkpWVZBXYlNLsd2Sikaa11cZBJRvjmHK2KxAADoa3MaSybIHLoj5trKuMKojJtnUwfTrtd2ZA72UTEXWuYzdtQTyY9GbUQKyfHJQ4pZCG0ezfvoWPbmX234dg5HFNv2R2Qu1cXAXMAoBYRajys1MgBM3xHeiRjRqZBjjACP7tb9U
      - FB_PAGE_APP_ID=518295607403711
      - INTERCOM_TOKEN=dG9rOmMxMWUyYzI0Xzg5ZWJfNDZkYV85OWVjX2UzODQ2NjhmYTBkZToxOjA=
      - INTERCOM_AI_USER_ID=7371007
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_PREFIX=ecc-prod
      - BUSYBEE_URL=https://app.brandtxt.io
      - BUSYBEE_API_KEY=Q/k/dRJ6Zp7mdXGrvErJVvpjnaedli7dP4J62RjtbKc=
      - BUSYBEE_CLIENT_ID=1af617b0-c047-49f2-a200-88337f3d7c7d
      - BUSYBEE_SENDER_ID=ECC
      - TZ=+08:00
    restart: always
  mysql-service:
    container_name: ecc-mysql-service
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vibetech@2024
      - TZ=Asia/Manila
    command: --default-time-zone='Asia/Manila'
  redis-service:
    image: redis:7-alpine
    ports:
      - 6379:6379
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis-service:6379
      - TZ=Asia/Manila
    ports:
      - '8081:8081'
