version: '3'
services:
  api-service:
    container_name: ecc-dev-api-service
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:3000
    volumes:
      - ./:/app
    environment:
      # - DB_HOST=mysql-service
      # - DB_USER=root
      # - DB_PASS=vibetech@2024
      - DB_HOST=74.208.164.136
      - DB_USER=root
      - DB_PASS=vibetech@2024
      - DB_NAME=ecc-services
      - OPENAI_API_KEY=sk-svcacct-15TLehrlgPdbUFIkr1iPT3BlbkFJJlYWRY1kt1EV1JlK8uEU
      - OPENAI_ASSISTANT_ID=asst_sDllhwXTNgRtJNbUtfSIe9Fq
      - OPENAI_VECTOR_STORE_ID=vs_68PUrGHdmxcqVdzZkwkBbIBY
      - FB_VERIFY_TOKEN=vibetech@2024
      - FB_PAGE_ACCESS_TOKEN=EAAO5JSsDSnEBO8ZCpNBTpGXiv79xr6ZB4utRis2i6c1b0WDuxTaaT9DuZC10oyAuKcjTjMa7Fanj89LhZBA8jHsZBqSP8msUIuBBtcnZBcSE6tn6K5tx2JgN4TG97QQQ1GSPbYnrMhVpzUQY4VOCrqcWhf7xnZC3R5ZCRZBitqFhJJRnlyJ8hQRHUOmha9ncNkTER
      - FB_PAGE_APP_ID=1047994216696433
      - INTERCOM_TOKEN=dG9rOmMxMWUyYzI0Xzg5ZWJfNDZkYV85OWVjX2UzODQ2NjhmYTBkZToxOjA=
      - INTERCOM_AI_USER_ID=7371007
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_PREFIX=ecc-dev
      - BUSYBEE_URL=https://app.brandtxt.io
      # - BUSYBEE_API_KEY=Q/k/dRJ6Zp7mdXGrvErJVvpjnaedli7dP4J62RjtbKc=
      # - BUSYBEE_CLIENT_ID=1af617b0-c047-49f2-a200-88337f3d7c7d
      # - BUSYBEE_SENDER_ID=ECC
      - BUSYBEE_API_KEY=nRH1dz+HS0d3M7WFOE9B9wluJA0c9ez++Ug8vKk0shQ=
      - BUSYBEE_CLIENT_ID=236cafeb-0bcd-41d4-bf95-69bf2c07167b
      - BUSYBEE_SENDER_ID="MBB Trial"
      - TZ=+08:00
    restart: always
  mysql-service:
    image: mysql:5.7
    container_name: ecc-dev-mysql-service
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vibetech@2024
      - TZ=Asia/Manila
    command: --default-time-zone='Asia/Manila'
  redis-service:
    image: redis:7-alpine
    container_name: ecc-dev-redis-service
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    container_name: ecc-dev-redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis-service:6379
      - TZ=Asia/Manila
    ports:
      - '8081:8081'
